#!/usr/bin/env bun
/**
 * Generates src/themes-embedded.ts from personas/themes/*.yaml
 * Run before bun compile to embed themes in the binary.
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const themesDir = join(import.meta.dir, "../../personas/themes");
const outFile = join(import.meta.dir, "../src/themes-embedded.ts");

const files = readdirSync(themesDir)
  .filter((f) => f.endsWith(".yaml"))
  .sort();

const entries: string[] = [];
for (const file of files) {
  const slug = file.replace(/\.yaml$/, "");
  const content = readFileSync(join(themesDir, file), "utf-8");
  // Escape backticks and ${} in template literals
  const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  entries.push(`  "${slug}": \`${escaped}\``);
}

const output = `// Auto-generated by scripts/embed-themes.ts — do not edit
// Contains ${files.length} theme YAML files embedded as strings

export const EMBEDDED_THEMES: Record<string, string> = {
${entries.join(",\n")}
};
`;

writeFileSync(outFile, output);
console.log(`Embedded ${files.length} themes into ${outFile}`);
